/**
 * Serene Bay — Content Loader v2
 * Individual markdown files per post, auto-discovered via manifest.json.
 *
 * HOW IT WORKS:
 *   1. Each post is its own .md file inside content/gallery/, content/flowers/,
 *      or content/literacy/.
 *   2. A GitHub Action (.github/workflows/generate-manifest.yml) scans those
 *      folders on every push and regenerates content/manifest.json.
 *   3. This script reads the manifest to know which files exist, then fetches
 *      each one individually.
 *   4. Just drop a new .md file in a folder, push, and it appears on the site.
 */

/* ── Frontmatter Parser ── */
function parseFrontmatter(fmText) {
  const result = {};
  const lines = fmText.split('\n');
  let currentKey = null;
  for (const line of lines) {
    const arrayMatch = line.match(/^\s*-\s+(.*)$/);
    if (arrayMatch && currentKey) {
      if (!Array.isArray(result[currentKey])) result[currentKey] = [];
      result[currentKey].push(arrayMatch[1].trim().replace(/^["']|["']$/g, ''));
      continue;
    }
    const match = line.match(/^(\w+):\s*(.*)$/);
    if (match) {
      result[match[1]] = match[2].trim().replace(/^["']|["']$/g, '');
      currentKey = match[1];
    }
  }
  return result;
}

/* ── Parse multiple items from one file (home.md, about.md) ── */
function parseMarkdownItems(text) {
  const items = [];
  const regex = /^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*?)(?=\n---\s*\n|$)/gm;
  let match;
  while ((match = regex.exec(text)) !== null) {
    const fm = parseFrontmatter(match[1].trim());
    const content = match[2].trim();
    items.push({ ...fm, _content: content });
  }
  return items;
}

/* ── Fetch helpers ── */
async function fetchMarkdown(path) {
  const res = await fetch(path);
  if (!res.ok) return null;
  return await res.text();
}

/* ── Fetch manifest (auto-generated by GitHub Action) ── */
async function fetchManifest() {
  const res = await fetch('/content/manifest.json');
  if (!res.ok) return { gallery: [], flowers: [], literacy: [] };
  return await res.json();
}

/* ── Fetch all posts from a folder (auto-discovered via manifest) ── */
async function fetchPosts(folder) {
  const manifest = await fetchManifest();
  const files = manifest[folder] || [];
  const posts = await Promise.all(files.map(async (file) => {
    const text = await fetchMarkdown('/content/' + folder + '/' + file);
    if (!text) return null;
    const items = parseMarkdownItems(text);
    return items[0] || null;
  }));
  return posts.filter(p => p !== null);
}

/* ── Fetch a multi-item file (home, about) ── */
async function fetchMarkdownItems(path) {
  const text = await fetchMarkdown(path);
  if (!text) return [];
  return parseMarkdownItems(text);
}

/* ── Render markdown to HTML (requires marked.js from CDN) ── */
function renderMd(text) {
  if (!text) return '';
  if (typeof marked !== 'undefined') return marked.parse(text);
  return text;
}

/* ── Load settings from content/site/settings.md ── */
async function loadSettings() {
  const text = await fetchMarkdown('/content/site/settings.md');
  if (!text) return null;
  const items = parseMarkdownItems(text);
  return items[0] || null;
}

async function initShell() {
  const s = await loadSettings();
  if (!s) return;
  document.title = (s.site_title || 'Serene Bay') + ' – ' + (s.tagline || '');
  document.querySelectorAll('[data-site-title]').forEach(el => {
    el.textContent = (s.site_title || 'Serene Bay').toUpperCase();
  });
  document.querySelectorAll('[data-tagline]').forEach(el => {
    el.textContent = s.tagline || '';
  });
  document.querySelectorAll('[data-hero-subtitle]').forEach(el => {
    el.textContent = s.hero_subtitle || '';
  });
  document.querySelectorAll('[data-footer-quote]').forEach(el => {
    el.innerHTML = `"${s.footer_quote || ''}"<br><cite>— ${s.footer_quote_author || ''}</cite>`;
  });
}

/* ── Navbar scroll + mobile menu ── */
function initNavbar() {
  const navbar = document.getElementById('navbar');
  if (navbar) {
    window.addEventListener('scroll', () =>
      navbar.classList.toggle('scrolled', window.scrollY > 40)
    );
  }
}

function toggleMenu() {
  document.getElementById('mobileMenu')?.classList.toggle('open');
}

/* ── Escape helper ── */
function esc(str) {
  return String(str || '').replace(/'/g, "\\'").replace(/"/g, '&quot;');
}
